var skills = [
"Abyssal Cry",
"Ancestral Protector",
"Ancestral Warchief",
"Anger",
"Animate Guardian",
"Animate Weapon",
"Arc",
"Arctic Armour",
"Arctic Breath",
"Assassin's Mark",
"Ball Lightning",
"Barrage",
"Bear Trap",
"Blade Vortex",
"Bladefall",
"Blast Rain",
"Blink Arrow",
"Blood Rage",
"Bone Offering",
"Burning Arrow",
"Caustic Arrow",
"Clarity",
"Cleave",
"Cold Snap",
"Conductivity",
"Contagion",
"Conversion Trap",
"Convocation",
"Cyclone",
"Decoy Totem",
"Desecrate",
"Determination",
"Detonate Dead",
"Detonate Mines",
"Devouring Totem",
"Discharge",
"Discipline",
"Dominating Blow",
"Double Strike",
"Dual Strike",
"Earthquake",
"Elemental Hit",
"Elemental Weakness",
"Enduring Cry",
"Enfeeble",
"Essence Drain",
"Ethereal Knives",
"Explosive Arrow",
"Fire Nova Mine",
"Fire Trap",
"Fireball",
"Firestorm",
"Flame Dash",
"Flame Surge",
"Flame Totem",
"Flameblast",
"Flammability",
"Flesh Offering",
"Flicker Strike",
"Freeze Mine",
"Freezing Pulse",
"Frenzy",
"Frost Blades",
"Frost Bomb",
"Frost Wall",
"Frostbite",
"Frostbolt",
"Glacial Cascade",
"Glacial Hammer",
"Grace",
"Ground Slam",
"Haste",
"Hatred",
"Heavy Strike",
"Herald of Ash",
"Herald of Ice",
"Herald of Thunder",
"Ice Crash",
"Ice Nova",
"Ice Shot",
"Ice Spear",
"Ice Trap",
"Immortal Call",
"Incinerate",
"Infernal Blow",
"Kinetic Blast",
"Lacerate",
"Leap Slam",
"Lightning Arrow",
"Lightning Strike",
"Lightning Tendrils",
"Lightning Trap",
"Lightning Warp",
"Magma Orb",
"Mirror Arrow",
"Molten Shell",
"Molten Strike",
"Orb of Storms",
"Phase Run",
"Poacher's Mark",
"Portal",
"Power Siphon",
"Projectile Weakness",
"Puncture",
"Punishment",
"Purity of Elements",
"Purity of Fire",
"Purity of Ice",
"Purity of Lightning",
"Rain of Arrows",
"Raise Spectre",
"Raise Zombie",
"Rallying Cry",
"Reave",
"Reckoning",
"Rejuvenation Totem",
"Righteous Fire",
"Riposte",
"Searing Bond",
"Shield Charge",
"Shock Nova",
"Shockwave Totem",
"Shrapnel Shot",
"Siege Ballista",
"Smoke Mine",
"Spark",
"Spectral Throw",
"Spirit Offering",
"Split Arrow",
"Static Strike",
"Storm Call",
"Summon Chaos Golem",
"Summon Flame Golem",
"Summon Ice Golem",
"Summon Lightning Golem",
"Summon Raging Spirit",
"Summon Skeletons",
"Summon Stone Golem",
"Sunder",
"Sweep",
"Tempest Shield",
"Temporal Chains",
"Tornado Shot",
"Vaal Arc",
"Vaal Burning Arrow",
"Vaal Clarity",
"Vaal Cold Snap",
"Vaal Cyclone",
"Vaal Detonate Dead",
"Vaal Discipline",
"Vaal Double Strike",
"Vaal Fireball",
"Vaal Flameblast",
"Vaal Glacial Hammer",
"Vaal Grace",
"Vaal Ground Slam",
"Vaal Haste",
"Vaal Ice Nova",
"Vaal Immortal Call",
"Vaal Lightning Strike",
"Vaal Lightning Trap",
"Vaal Lightning Warp",
"Vaal Molten Shell",
"Vaal Power Siphon",
"Vaal Rain of Arrows",
"Vaal Reave",
"Vaal Righteous Fire",
"Vaal Spark",
"Vaal Spectral Throw",
"Vaal Storm Call",
"Vaal Summon Skeletons",
"Vengeance",
"Vigilant Strike",
"Viper Strike",
"Vitality",
"Vortex",
"Vulnerability",
"Warlord's Mark",
"Whirling Blades",
"Wild Strike",
"Wither",
"Wrath",
"Added Chaos Damage Support",
"Added Cold Damage Support",
"Added Fire Damage Support",
"Added Lightning Damage Support",
"Additional Accuracy Support",
"Blasphemy Support",
"Blind Support",
"Block Chance Reduction Support",
"Blood Magic Support",
"Bloodlust Support",
"Cast On Critical Strike Support",
"Cast on Death Support",
"Cast on Melee Kill Support",
"Cast when Damage Taken Support",
"Cast when Stunned Support",
"Chain Support",
"Chance to Flee Support",
"Chance to Ignite Support",
"Cluster Traps Support",
"Cold Penetration Support",
"Cold to Fire Support",
"Concentrated Effect Support",
"Controlled Destruction Support",
"Culling Strike Support",
"Curse On Hit Support",
"Elemental Focus Support",
"Elemental Proliferation Support",
"Empower Support",
"Endurance Charge on Melee Stun Support",
"Enhance Support",
"Enlighten Support",
"Faster Attacks Support",
"Faster Casting Support",
"Faster Projectiles Support",
"Fire Penetration Support",
"Fork Support",
"Fortify Support",
"Generosity Support",
"Greater Multiple Projectiles Support",
"Hypothermia Support",
"Ice Bite Support",
"Increased Area of Effect Support",
"Increased Burning Damage Support",
"Increased Critical Damage Support",
"Increased Critical Strikes Support",
"Increased Duration Support",
"Innervate Support",
"Iron Grip Support",
"Iron Will Support",
"Item Quantity Support",
"Item Rarity Support",
"Knockback Support",
"Less Duration Support",
"Lesser Multiple Projectiles Support",
"Life Gain on Hit Support",
"Life Leech Support",
"Lightning Penetration Support",
"Mana Leech Support",
"Melee Damage on Full Life Support",
"Melee Physical Damage Support",
"Melee Splash Support",
"Minefield Support",
"Minion Damage Support",
"Minion Life Support",
"Minion Speed Support",
"Minion and Totem Elemental Resistance Support",
"Multiple Traps Support",
"Multistrike Support",
"Physical Projectile Attack Damage Support",
"Physical to Lightning Support",
"Pierce Support",
"Point Blank Support",
"Poison Support",
"Power Charge On Critical Support",
"Ranged Attack Totem Support",
"Rapid Decay Support",
"Reduced Mana Support",
"Remote Mine Support",
"Slower Projectiles Support",
"Spell Echo Support",
"Spell Totem Support",
"Stun Support",
"Trap Cooldown Support",
"Trap Support",
"Trap and Mine Damage Support",
"Void Manipulation Support",
"Weapon Elemental Damage Support"
];